
name: Java CI

#workflow trigger
on: [push]

#job configuration
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # check out my repository so workflow can access the content
      - uses: actions/checkout@v2
      # set up JDK17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      # run Maven to build project and download necessary dependencies such as JUnit
      - name: Build with Maven
      #  run: mvn -B package --file pom.xml
      # specifically run maven test phase to execute JUnit tests
      - name: Run JUnit Tests
        run: mvn test
      # Re-run Maven using the -X switch to enable full debug logging
      # mvn test -X
